### ISSUE TITLE
Make experience points count more subtle in the block

### ISSUE THREAD

**Issue by FMCorz** [FMCorz/moodle-block_xp#72]
I have received a request to be able to:

- Hide the total amount of XP in the block
- Make the "XP to go" more subtle in the block's progress bar

Those changes were motivated by other users who felt that there was a need for a better emphasis on the experience points gained overall. One of the reasonings was so that students did not feel like they had to start from zero after every level.

I'm inline with the request of being able to hide the total amount of XP. Regarding the progress bar, it is not as straightforward as the number attached to it does not always make sense without some wording to it. I have investigated quite a few designs and this one seemed to be the most understandable for a majority of students.

Before a patch is available, here are two `customcss` (raw SCSS if in Boost) snippets you can make use of:

__Hide the total__
```css
.block_xp .xp-total { display: none; }
```

__Dim the XP to go__
```css
.block_xp .xp-togo { color: #999; }

/* Optionally, to hide the text "XP to go" */
.block_xp .xp-togo .xp-togo-txt { display: none; }
```
